Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using LogViewer.Models;
using Microsoft.AspNetCore.Mvc;

namespace LogViewer.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult Index() => View();

        public async Task<JsonResult> GetDatas(string schema, string type, DateTime date){
            var repo = new RepoLogs(schema);
            return Json(await repo.GetChart(type,date));
        }
    }
}

Views/Shared/Partials/_Footer.cshtml
<hr />
        <footer>
            <p>&copy; 2018 - LogViewer</p>
        </footer>

Views/Shared/Partials/_Meta.cshtml
<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogViewer</title>

Views/Shared/Partials/_Nav.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LogViewer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Chart" asp-action="Index">Chart</a></li>
                </ul>
            </div>
        </div>
    </nav>